# Generated by Django 4.1.1 on 2022-09-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('MCA', 'MCA'), ('II', 'IT'), ('COMPUTER', 'COMPUTER')], max_length=10),
        ),
    ]
