# Generated by Django 4.1.1 on 2022-09-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stdid',
            field=models.IntegerField(unique=True),
        ),
    ]
